# Generated by Django 4.2.7 on 2023-12-08 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('our_price', models.FloatField()),
                ('real_price', models.FloatField()),
                ('description', models.TextField()),
                ('main_img', models.ImageField(upload_to='main_imgs/')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.maincategory')),
            ],
        ),
    ]
