# Generated by Django 4.2.7 on 2023-12-15 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_customerinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerInfo',
        ),
    ]
