# Generated by Django 4.2.7 on 2023-12-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_customerinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='first_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='last_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='phone',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='user_email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='user_password',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
