# Generated by Django 4.2.7 on 2023-12-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_alter_customerinfo_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_active',
            field=models.BooleanField(default=True),
        ),
    ]
