# Generated by Django 4.2.7 on 2023-12-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_variant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
