# Generated by Django 4.2.7 on 2023-12-19 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_product_product_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_variant',
        ),
    ]
