# Generated by Django 4.2.7 on 2023-12-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_variant_description_variant_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
