# Generated by Django 4.2.7 on 2023-12-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_delete_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
