# Generated by Django 4.2.7 on 2023-12-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_product_base_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_feature',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
