# Generated by Django 4.2.7 on 2023-12-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0022_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
