# Generated by Django 4.2.7 on 2023-12-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0024_cart_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='payment_method',
            field=models.CharField(default='Cash on Delivery', max_length=100),
        ),
    ]
