# Generated by Django 4.2.7 on 2024-01-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0029_orderplaced_discount_alter_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='discounted_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
