# Generated by Django 4.2.7 on 2024-01-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0030_orderplaced_discounted_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='discounted_total',
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='discount_status',
            field=models.BooleanField(default=False),
        ),
    ]
