# Generated by Django 4.2.7 on 2024-01-06 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0032_usercoupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercoupon',
            old_name='coupoun',
            new_name='coupon',
        ),
    ]
