# Generated by Django 4.2.7 on 2024-01-10 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0035_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercoupon',
            old_name='is_active',
            new_name='is_used',
        ),
    ]
