# Generated by Django 4.2.7 on 2024-01-13 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0037_order_orderplaced_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.order'),
        ),
    ]
