# Generated by Django 4.2.7 on 2024-01-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0039_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On the way', 'On the way'), ('delivered', 'delivered'), ('Cancelled', 'Cancelled'), ('requested for cancellation', 'requested for cancellation'), ('requested for return', 'requested for return'), ('returned', 'returned')], default='Accepted', max_length=50),
        ),
    ]
