# Generated by Django 4.2.7 on 2024-01-17 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0041_order_payment_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='payment_method',
            new_name='payment_status',
        ),
    ]
